services:
  gamedaybot:
    build:
      context: .
    restart: always
    environment:
      #This is your Webhook URL from the Discord Settings page (REQUIRED)
      DISCORD_WEBHOOK_URL: ""
      #ESPN league id (REQUIRED)
      LEAGUE_ID: 
      # #When the bot will start paying attention and sending messages to your chat.
      # START_DATE:
      # #When the bot will stop paying attention and stop sending messages to your chat.
      # END_DATE:
      # #ESPN League year
      LEAGUE_YEAR:
      # #Required for private leagues. See Private Leagues Section for documentation
      ESPN_S2: ""
      SWID: ""
      # #The timezone that the messages will look to send in. (America/New_York by default)
      # TIMEZONE:
      # #The message that the bot will say when it is started (leave blank for no message)
      # INIT_MSG:
      # #If set to True, when extra trophies will be included when final score update runs
      # EXTRA_TROPHIES: 
      # #If set to True, waiver reports will run (Wednesdays only by default)
      # WAIVER_REPORT:
      # #If set to True, waiver reports will run daily
      # DAILY_WAIVER:
      # #If set to True, monitor and inactive reports will run on Friday and Sunday morning, respectivvely
      # MONITOR_REPORT: 
      # #Assign a score value for the monitor report to warn users about (3 by default)
      # SCORE_WARNING:
      # #Largest projected point difference that still counts as a close matchup (15 by default)
      # CLOSE_SCORES_THRESHOLD:
      # #See User and Emote IDs section for documentation on these
      # USERS: ""
      # EMOTES: ""
      # #Used for troubleshooting--set to 1 so bot will provide test output instead
      # TEST: 0
