name: Run tests on PRs and commits

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - master
  workflow_dispatch:

env:
  BOT_ID: 916ccfd76a7fda25c74d09e1d5
  LEAGUE_ID: 164483
  TEST_TAG: user/test_build:test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-test.txt

      - name: Test with pytest
        run: pytest

      - name: Upload coverage (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
        continue-on-error: true
